import type { Book } from "./types";

export const BOOKS: Book[] = [
  {
    id: "b1",
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    year: 1965,
    rating: 4.8,
    pages: 688,
    description: "A desert world, political intrigue, and a rise to power.",
    coverColor: "#d9a441",
  },
  {
    id: "b2",
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Sci-Fi",
    year: 2021,
    rating: 4.9,
    pages: 496,
    description: "A lone astronaut wakes up on a mission to save humanity.",
    coverColor: "#7aa6ff",
  },
  {
    id: "b3",
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Technology",
    year: 2008,
    rating: 4.5,
    pages: 464,
    description: "A practical guide to writing maintainable software.",
    coverColor: "#5fd3bc",
  },
  {
    id: "b4",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    genre: "Technology",
    year: 1999,
    rating: 4.7,
    pages: 352,
    description: "Advice for building better software and better habits.",
    coverColor: "#9d7cff",
  },
  {
    id: "b5",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "History",
    year: 2011,
    rating: 4.6,
    pages: 498,
    description: "A broad look at the history of humankind.",
    coverColor: "#ff9f6e",
  },
  {
    id: "b6",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Business",
    year: 2018,
    rating: 4.8,
    pages: 320,
    description: "Small changes that lead to big results over time.",
    coverColor: "#ff7d7d",
  },
  {
    id: "b7",
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Business",
    year: 2016,
    rating: 4.4,
    pages: 304,
    description: "How focused work can improve productivity and output.",
    coverColor: "#82c96d",
  },
  {
    id: "b8",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Mystery",
    year: 2019,
    rating: 4.3,
    pages: 336,
    description: "A psychological thriller with a shocking reveal.",
    coverColor: "#ffcf5a",
  },
  {
    id: "b9",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "Psychology",
    year: 2011,
    rating: 4.4,
    pages: 512,
    description: "Two systems of thought and how they shape decisions.",
    coverColor: "#8fd3ff",
  },
  {
    id: "b10",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1937,
    rating: 4.9,
    pages: 310,
    description: "A journey through Middle-earth with dragons and treasure.",
    coverColor: "#b7a0ff",
  },
  {
    id: "b11",
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    year: 2018,
    rating: 4.7,
    pages: 334,
    description: "A memoir about family, identity, and education.",
    coverColor: "#ffa9c9",
  },
  {
    id: "b12",
    title: "The Martian",
    author: "Andy Weir",
    genre: "Sci-Fi",
    year: 2011,
    rating: 4.7,
    pages: 369,
    description: "An astronaut survives alone on Mars using ingenuity.",
    coverColor: "#ffb36b",
  },
];
